### ISSUE TITLE
time series error

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#156]
@aspina7  any chance you can investigate this? Came in on a Google review from a person at OCA (intermediate-advanced R user) 

The Fourier terms calculation hits error. may be good to check in cases it is same for every one.
counts <- counts %>% 
  mutate(
    ## combine fourier terms for weeks prior to  and after 2010 cut-off date
    ## (nb. 2011 fourier terms are predicted)
    fourier = rbind(
      ## get fourier terms for previous years
      fourier(
        ## only keep the rows before 2011
        filter(counts, 
               epiweek <= cut_off), 
        ## include one set of sin cos terms 
        K = 1
        ), 
      ## predict the fourier terms for 2011 (using baseline data)
      fourier(
        ## only keep the rows before 2011
        filter(counts, 
               epiweek <= cut_off),
        ## include one set of sin cos terms 
        K = 1, 
        ## predict 52 weeks ahead
        h = num_weeks
        )
      )
    )
Error: Problem with `mutate()` input `fourier`.
x Input `fourier` can't be recycled to size 276.
i Input `fourier` is `rbind(...)`.
i Input `fourier` must be size 276 or 1, not 328.

**Comment by aspina7** [comment]
the issue here is that the number of weeks that we are asking the fourier function to calculate for is more than those that exist in our dataset (so binding in to a variable does not work). 
What needs to happen is to add blank rows to the dataset (only filling the week variable) - so that this can work. 
Have been working to make a template in the r4epis repo, starting a package called epitsa - the code for adding weeks to dataset and calculating an appropriate fourier is [here](https://github.com/R4EPI/epitsa/blob/master/inst/rmarkdown/templates/tsa_multiproj/skeleton/skeleton.Rmd#L1568)

What I need to do on the handbook walkthrough is to pretend we are in a week half-way through 2011, remove all the weeks from the original dataset after that time and then upate the code with that from the epitsa template.

**Comment by aspina7** [comment]
this should be fixed now, is there an email for the error submission? think is probs the epi in ssudan, can message isidro or pat if needed

**Comment by nsbatra** [comment]
berhe.estay.com
