### ISSUE TITLE
Feedback: Missing data

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#68]
**Please leave comments and suggested changes for the "Missing data" page here**

**Comment by PBBlomquist** [comment]
Hi, and well done for this chapter.

Comments:

- How about 'quantifying missingness' as a subtitle rather than 'statistics'?
- To elaborate on the point 'remember that NA means missing and that "" or " " will register as non-missing (note you have a typo in that point), can you add to the preparation a cleaning step where you identify what is missing and replace with NA?
- gg_mis_var is fabulous and I'm annoyed I didn't know about it earlier. Can you do multiple colours in the same column (rather than just faceting)? Maybe worth mentioning if you can't, for the ggplot folk who expect to be able to add color or fill arguments.
- Can you combine 15.5, 15.6, and 15.7 to 'using data with missing values'? 
- I think parts of 15.8 can go up to the top as an explanation of why one needs to understand the missingness and the types - it's not only relevant to the imputation.

**Comment by nsbatra** [comment]
@PBBlomquist  Thanks for these! Implemented now. :-)
Better late than never,
