### ISSUE TITLE
Feedback: Grouping data

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#69]
**Please leave comments and suggested changes for the "Grouping data" page here**

**Comment by PBBlomquist** [comment]
Hello grouping expert.

My comments:

- Very nice explanations. I like how you explain the way you can 'see' groups.
- Wondering if 'grouping data' is the best title here, because really it's about basic summary stats? Otherwise I can see some of the content is better moved into the 'descriptive analysis' section, or at least more cross referencing between the two. Especially when it starts going into the adding totals.
- Some typos (rogue bullet point under 11.1, 'contitutes' under 11.3)
- For 11.5, can add that grouping vars will be automatically included when selecting columns to make a smaller dataset.
- What is the benefit of using summarise_across(.cols = c(var1, var2)), .fns = mean) over summarise(var1 = mean(var1), var2 = mean(var2))? Perhaps where there are lots of columns to summarise, this can be time saving as you can even write c(1:20) rather than all 20 names. Worth adding?

**Comment by nsbatra** [comment]
Thanks! Implemented now.
