### ISSUE TITLE
Feedback: De-duplication

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#72]
**Please leave comments and suggested changes for the "De-duplication" page here**

**Comment by pbkeating** [comment]
This is a super useful page and learned some new approaches to deduplication from it! :)

- [ ] Minor point but there are 17 observations in the table and not 18. One of the Adam rows has been removed but also one of the Amrish rows (record ID 3)
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/deduplication.Rmd#L136


- [ ] Maybe just me, but I get the feeling I should know this database better and know how many Brian's and Amrish's there are. Maybe a summary table illustrating how many records per name so that we, as the reader, already have that in their minds. I find myself going back and forth to the first table to find out what was normal and what has now changed
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/deduplication.Rmd#L165

- [ ] Not sure it's supposed to be key_vars here?
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/deduplication.Rmd#L398

**Comment by nsbatra** [comment]
@pbkeating thanks for these! Implemented now.
