### ISSUE TITLE
Feedback: Moving averages

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#77]
**Please leave comments and suggested changes for the "Moving averages" page here**

**Comment by PBBlomquist** [comment]
Hello!

This page is very nicely explained/walked through. Some comments:

- 'Calculate-then-display' - not sure about this title. How about 'calculate in dataset' as opposed to 'calculate within ggplot', or simply subheadings by package name ("Calculate with slider" vs "calculate with tidyquant within ggplot")
- You can explain under 'window size' that if the period is not complete, it will be a missing value. Also if you set complete to F,  it will use the available rows.
- Would help if for first example you specify how it's sorted/arranged, maybe add in code for this. Looks like it's a rolling mean among patients in order of their date of onset - you could also maybe add a 'order' column to make this clear. 
- Grouped data - I think it needs more of an intro. I.e. 'You can group your data so that the moving average is calculated within groups.' I realise the example is just to show the NAs introduced at the beginning of each month, but it's otherwise a weird example without much practical benefit (grouping on time when the moving average is already a function of time). Grouping by another variable such as hospital would make more sense - could even then ggplot() the separate lines (if you're bothered :) ). 
- Helpful 'danger' message about versions 
- slide_index is super good!! Thank you for sharing. I've always used 'complete' to add in the missing rows, but can see this is not necessary :). Can you explicitly add that it assumes those missing days have 0 values (rather than it "accounts for them")? Can it fill in for the days before the start date too?
- Also nice to see tidyquant. Worth mentioning if it recognises missing days also.

**Comment by nsbatra** [comment]
Thanks for these! Implemented now.
