### ISSUE TITLE
Feedback: Transmission chains

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#87]
**Please leave comments and suggested changes for the "Transmission chains" page here**  

Lead author is @finlaycampbell

**Comment by Natalie-Fischer** [comment]
Hi Finlay, 

here are some minor comments on your transmission chain chapter. Overall I really like it and I think it contains everything one needs to know and is very clear. I have worked a bit with epicontacts during my EVD deployment with Marie-Amelie and Neale, so I am a beginner in this package if you want ;-)

**35.1 Overview:** 
few suggestions, add a color circle for grey as well (assuming unknown?), instead of f and m write out female and male, as you do for death and recover. If this is a real example it could be nice to mention what outbreak or pathogen it was.

**35.2 Packages and data:**
After you install the development version of epicontacts, you could add a line to load the package as well, as they will have to do this in the future.

**35.2.2 Creating an epicontacts object:**
Very clear, no comments.

**35.3 Handling:**
Maybe add a bit more to the headline? Handling of what?

**35.3.1 Subsetting**
It is not obvious that "We can see that only two known transmission links fit that specification" results in the "nrow(sub_attributes$contacts)" = 4 output. I would also show the sub_attributes$contacts - it may be more visual than seeing the number 4. 

**35.3.2 Accessing IDs**:
**to** IDs in the “to”  column of contact dataset - is missing a **:** after the bold to

 **35.4.1 Basic plotting :**
I like that you repeat the subset and thin function here. That makes it stick.
You don't mention anything about selection by the drop down menu here or in the following part

**35.4.1.1 Visualising node attributes:**
Same comment as on top: I would add another color for "Pending/Unknown" = grey, and leave female and male as a whole word as you have enough space here and don't really gain anything by shortening it.  
You don't mention anything about selection by the drop down menu here.

**35.4.1.2 Visualising edge attributes:**
The difference in edge_width is not easy to see here. Can you add one or two more extreme examples just for visualization purposes? Also there is no legend for edge_width.

**35.4.2.1 Specifying transmission tree shape:**
"The position of unconnected cases (i.e. with no reported contacts) is specified using the unlinked_pos argument." Can you add an unlinked case or two just to show how it would look?

**35.4.3 Timelines:**
"You can also case timelines to the network" - I think there is a word missing "add" ?
Very nice - I like how you commented out each line in the big plot for a good recap.

**35.5.1 Summarising:**
" this means that **the** we do not have linelist data on a significant number of cases involved in these transmission chains."
- there is one word too much.

**35.5.3 Identifying clusters:**
"The get_clusters() function can be used **for** to identify" - one word too much
After the "table table(clust$cluster_size)" maybe add a sentence about what we are seeing: 1536 unlinked cases and 42 clusters of 14 members something like that.
"epic <- get_clusters(epic)" does this add the cluster part to the epicontacts object or replace it? 

**35.5.4 Calculating degrees:**
"Which individuals have the **ten** most contacts?" - I think you mean which **ten** individuals have the most contacts?

**Comment by PBBlomquist** [comment]
Hi Finlay,

Minor feedback from me: Can you add in instruction on how to remove the drop down menu when saving as an image? Any other small formatting things (like legend width) are very helpful!

Paula
