### ISSUE TITLE
Feedback: Phylogenetic trees

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#88]
**Please leave comments and suggested changes for the "Phylogenetic trees" page here**  

Lead author is @Natalie-Fischer

**Comment by bailey-c** [comment]
Hi team - I've made some suggestions for the Phylogenetic trees page.

38.1 - preparation

- If you are describing how to load packages, should you describe how to install packages (or is this covered in R basics)? You could, for example, add “you can install packages from base R using the syntax install.packages().

- I am currently unable to download the .nwk file from the GitHub repo and the file is not supported using rio::import.

- minor point, but I would replace tip.labels with Tip labels here :- “We clean and inspect our data: In order to assign the correct sample data to the phylogenetic tree, the Sample_IDs in the sample_data file need to match the tip.labels in the tree file:”

- Are you planning to incorporate the linelist code (#sample_data <- linelist::clean_data(sample_data, protect = c(1, 3:5))) as code block? Or is this just an example of how one would clean the data? I would add linelist to the dependency list (p_load) if you are doing the first.

- A suggestion for checking if the sampleIDs and tip.labels match is to use something like: 

sample_data$Sample_ID %in% tree$tip.label

You will then get a logical vector of TRUE or FALSE where they do to do not match

This command will give you a list of sample IDs that are on the tree:
sample_data$Sample_ID[tree$tip.label %in% sample_data$Sample_ID]

And this will tell you any sample IDs that are not on the tree:
sample_data$Sample_ID[!tree$tip.label %in% sample_data$Sample_ID]

something that could be incorporated if you wanted to do this further

38.2 - visualisation

- Bugfix:
By taking the code line 

ggtree(tree, layout="circular", branch.length='none') %<+% sample_data + # the %<+% is used to add your dataframe with sample data to the tree
  aes(color=I(Belgium))+     # color the branches according to a variable in your dataframe
  scale_color_manual(
    name = "Sample Origin”…

as it is - you get the error message:
 
Error in structure(x, class = unique(c("AsIs", oldClass(x)))) : 
  object 'Belgium' not found

Suggest the following change (add “ ”):
aes(color=I("Belgium”))

38.3.2 - rotating nodes
- For the following code block (which is in plain text at the moment):

R> p1 <- p + geom_hilight(39, "steelblue", extend =0.0015) # highlights the node 39 in blue

Forms the error message:

Error: $ operator is invalid for atomic vectors

38.4 - more complex trees 

- I’d remove the hashtags to visualise the trees in the codeblock
# h1
# h3

I hope the comments are useful! Overall it is a great chapter which displays the amazing things you can do with tree manipulation and visualisation. It might be worth elaborating on packages that create tree outputs in the various file formats (e.g. iqtree http://www.iqtree.org) but as an R handbook it might be beyond the scope to do this.

BW

Chris

**Comment by Natalie-Fischer** [comment]
Thanks so much Chris! Really helpful suggestions :-) 

- As for the install.package() I think this will be explained earlier, but I added a comment reminding people to first install
- Why you can't download the .nwk file I don't know. Maybe Neale has an idea?
- I deleted the clean_data part as it was an old remnant and is not really needed here anymore.
- I incorporated your suggestion for TRUE FALSE between sample ID and tip label - good idea.
- I updated the chunk on rotating and flipping nodes - it works for me on my computer. Neale can you double check if it works for you now as well?
- I also fixed some typos and went over all the text ;-)
