### ISSUE TITLE
Feedback: Interactive plots

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_eng#89]
**Please leave comments and suggested changes for the "Interactive plots" page here**  

Lead author is @isaac-florence

**Comment by pbkeating** [comment]
- [ ] Super basic, but maybe good to say that the interactivity requires html format and won't work on say pdf


- [ ] Worth also showing the pacman part for this page and trying to consistently show which packages are required in the preparation section of each page?
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L45-L50



- [ ]  spelling mistake on be
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L46



- [ ] Need to stop messages appearing with this chunk

https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L130-L132



- [ ] Maybe link to GIS page if this topic is covered ?
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L195



- [ ] Not sure if we want to load all the relevant packages in the preparation phase rather than here?
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L201



- [ ]  We mix importing using here and not using... just a thought? Do we want to only show importing not using here?
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L204-L207

- [ ] Spelling mistake on sovereignty
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L220


- [ ] Have we introduced the idea of purrr anywhere?
https://github.com/nsbatra/Epi_R_handbook/blob/09a634578eb56d14e5ec3fd1d0e701a172361886/new_pages/interactive_plots.Rmd#L226

- [ ] There is no data plotted in the final map of this section

**Comment by nsbatra** [comment]
@isaac-florence will you have any time to address these?

**Comment by isaac-florence** [comment]
*Apologies for my embarrassingly slow response*

Thank you very much @pbkeating for your really helpful comments. It looks like a kind soul has implemented most of these changes but I have made some other adjustments too. The one thing I can't fix is why the map will not display when it works just fine for me, and it did in the previous version (before moving to bookdown). I will investigate further
